name: MinecraftVoiceChat
version: 1.0.0
description: Proximity-based voice chat system for Minecraft
author: YourName
main: com.yourname.minecraftvoicechat.MinecraftVoiceChatPlugin
api-version: 1.19

commands:
  voicechat:
    description: Get your voice chat link
    usage: /voicechat
  voicechat-reload:
    description: Reload the voice chat configuration
    usage: /voicechat-reload
    permission: voicechat.admin

permissions:
  voicechat.admin:
    description: Allows reloading the voice chat configuration
    default: op
